### ISSUE TITLE
Support for SET operations

### ISSUE THREAD

**Issue by dschulz** [soulwing/tnm4j#1]
Hi,

It looks like support for SNMP SET operations is not implemented, but the README mentions

_In addition to the get method, the context provides methods to support all of the fundamental SNMP operations: GET, GETNEXT, GETBULK, and  SET._

Am I missing something? Thanks!

**Comment by ceharris** [comment]
No, you're not missing anything.  Since I haven't needed SET, yet, I haven't implemented it.  Should be pretty straightforward.  If you feel like taking a shot at doing it, I'll be happy to try to guide you through it.

**Comment by dschulz** [comment]
Hi! Thanks for responding. I'll study the code to see if I can be of any help. Thanks again!

**Comment by ceharris** [comment]
Don't know if you're still interested, but I have added support for SET.  It's had little testing at this point, so if you have some use cases and would be willing to test, I'd appreciate it.
