### ISSUE TITLE
asyncwalk keeps retrying on TimeoutException

### ISSUE THREAD

**Issue by scarr** [soulwing/tnm4j#11]
When performing an asyncwalk and the host does not respond and the response.get() throws a timeoutexception, the host is retried indefinitely even if the TimeoutException is handled.

**Comment by ceharris** [comment]
This is a known issue, which I'd completely forgotten about. There's a FIXME marked around line 103 of AbstractAsyncWalker. We invoke the callback in a separate thread from the one that is being driven by the walk. In that separate thread, we need to allow the callback to throw an exception that would be caught and would be used to signal to the thread driving the walk that it should bail out. Shouldn't be too awfully hard; it was just overlooked in the current implementation.

**Comment by ceharris** [comment]
fixed in 24c98dc

will be included in release 1.0.11
