### ISSUE TITLE
SNMP4J Provider support for SNMP V1

### ISSUE THREAD

**Issue by scarr** [soulwing/tnm4j#12]
Is there any support for SNMP v1 Get Requests in the SNMP4J Provider?

**Comment by ceharris** [comment]
As far as I can tell, the differences between an SNMPv1 GET and and SNMPv2c GET are academic and probably negligible. Do you have an agent that respond to requests sent using an SNMPv2c target?

**Comment by SiPad** [comment]
I have also a target that does not respond to SNMPv2c. Normal get and getnext requests are both working with a SNMPv1-Target (Tested with native snmp4j and mibble). Is there a workaround for activating SNMPv1?

**Comment by ceharris** [comment]
Resolved by commit 1820ebb.
