### ISSUE TITLE
Unable to set authNoPriv security level

### ISSUE THREAD

**Issue by spidloun** [soulwing/tnm4j#24]
Hello,
I am trying to authenticate against device using SNMPv3 with auth but no encryption (authNoPriv mode).

However, if I create a `SimpleSNMPv3Target` with `setPrivType` set to `null`, I got a `NullPointerException`.

I went through the source code and I have come to a conclusion, that it cannot be done. If I look at this line https://github.com/soulwing/tnm4j/blob/1ad1a15562f4ca79a11c745faf38273cca75dd05/src/main/java/org/soulwing/snmp/provider/snmp4j/UserTargetStrategy.java#L80 I understand, that the `setPrivType` should be set to `null` in order to get authNoPriv security level as stated on the very next line. 

However, if I do that, the code fails because of this line https://github.com/soulwing/tnm4j/blob/1ad1a15562f4ca79a11c745faf38273cca75dd05/src/main/java/org/soulwing/snmp/provider/snmp4j/UserTargetStrategy.java#L70 as it expects the `privType` to be non-null in every case.

As a consequence, the desired security level is never reached.

Additional notes: `NullPointerException` is obviously fired by the switch-case statement in `privType` function here https://github.com/soulwing/tnm4j/blob/1ad1a15562f4ca79a11c745faf38273cca75dd05/src/main/java/org/soulwing/snmp/provider/snmp4j/UserTargetStrategy.java#L108
As switch-case is known not to accept null`s until Java v18, this will not work.

**Comment by ceharris** [comment]
Fixed by #26
