### ISSUE TITLE
Utilize the repo to load Custom MIB file 

### ISSUE THREAD

**Issue by pranith-shabodi** [soulwing/tnm4j#25]
Hello,

Can I use this Code base as dependency in my Organization project. My requirement is to load custom MIB File and Add the MIB to SNMPAgent from snmp4j. @ceharris Please let me know if i can do this action. Do i need any license to use this repo.

Thanks

**Comment by ceharris** [comment]
If you're building a product that embeds an SNMP agent, this library might not be the right choice for you. This library is designed to facilitate the development of application programs that utilize (as a client) the properties of SNMP agents embedded in other products.

This library is an open source product licensed under the terms of the [GNU Public License](https://github.com/soulwing/tnm4j/blob/master/LICENSE).

**Comment by pranith-shabodi** [comment]
@ceharris  I Thought this library has MIB Parser which can parse custom MIBs. One help do you know any library which is useful for development of SNMP agent with parsing capability and load it in Agent server. 

Thanks

**Comment by ceharris** [comment]
At noted in the README, this project uses the (excellent) open-source [Mibble](https://mibble.org/) MIB parser.
