### ISSUE TITLE
Dependencies wont download.

### ISSUE THREAD

**Issue by komcrad** [soulwing/tnm4j#6]
I am unable to build.
mvn compile freezes on 
`Downloading from mibble: https://nexus.cns.vt.edu/nexus/content/groups/public/net/percederberg/mibble-parser/2.9.3/mible-parser-2.9.3.pom`
Any ideas?

**Comment by ceharris** [comment]
As I mentioned in another thread, the Mibble author doesn't currently provide artifacts via Maven Central. I'm [making progress](https://github.com/cederberg/mibble/issues/30) on getting that to change.

Meanwhile, if you download the two jar files for Mibble and install them in your local maven repo using `mvn install:install-file`, you can get a build to run.

**Comment by komcrad** [comment]
I must have accidentally installed the dependencies awhile back. I couldn't figure out why it just started failing out of the blue. My mistake.
