### ISSUE TITLE
pom.xml repository offline

### ISSUE THREAD

**Issue by hugleo** [soulwing/tnm4j#7]
respository https://nexus.cns.vt.edu/nexus/content/groups/public/ is offline

**Comment by komcrad** [comment]
I believe this is related to the issue of mibble not being in a repository.

**Comment by hugleo** [comment]
can't downloading from: https://nexus.cns.vt.edu/nexus/content/groups/public/net/percederberg/mibble-parser/2.9.3/mibble-parser-2.9.3.pom

Is mibble-parser-2.9.3.pom the same that mibble-2.9.3.pom. If is we can use opennms repository:

http://maven.opennms.org/content/groups/opennms.org-release/net/percederberg/mibble/mibble/2.9.3/mibble-2.9.3.pom

**Comment by filirnd** [comment]
Same problem !

**Comment by ceharris** [comment]
Switched to OpenNMS repository for Mibble; release 1.0.8 with that change should hit Maven Central in the next few hours.
