### ISSUE TITLE
Back to Apache License

### ISSUE THREAD

**Issue by WolfgangFahl** [soulwing/tnm4j#8]
It looks like this was originally under Apache License. I'd use this project if it would be available under Apache License. Could you make it dual licensed?

**Comment by ceharris** [comment]
I don't have an objection to dual licensing. However, the Mibble MIB parser on which this library depends uses the GPL license.

If Mibble's author is willing to dual license or change to the more liberal ASL, I'll be happy to follow suit.

**Comment by WolfgangFahl** [comment]
I see - Mibble is commercially oriented so I doubt the change will happen. Can we replace Mibble with something else?

**Comment by ceharris** [comment]
MIB support is loaded using the ServiceLoader mechanism that was introduced in JDK 6. The `MibFactory` singleton is used to find a `MibProvider` instance. A `MibProvider` has a method that is used to get a `Mib` instance. The `Mib` interface and the interfaces referenced by it constitute the MIB API used internally by tnm4j.

**Comment by ceharris** [comment]
So yeah, if someone wanted to make an alternative MIB provider, I'll be happy to dual license.

**Comment by ceharris** [comment]
FWIW, I've found Per Cederberg of Mibble to be a pretty reasonable guy. I haven't inquired about the terms of his commercial license, because I haven't had need. But if the reason you want ASL for tnm4j is to make a commercial product, you might at least consider inquiring.

**Comment by komcrad** [comment]
For inquiry about re-licensing Mibble, perhaps LGPL would be a good request. Currently, it's under GPL 2.0 so he may really want the source code of any distributed code that uses his project. He may go for LGPL which would explicitly allow for dynamic linking in distribution without requiring linked code to be open sourced at all but he'd still have the requirement to have changes (when being distributed) in the mibble project contributed back.
Eg: if mibble used lgpl; maven project lists mibble as a dep, under lgpl you'd have explicit permission to use mibble and not open source your maven project and you could distribute your maven project under your own license. At least that's how I understand it.
